name: think_notion_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  path: ^1.8.0
  sqlite3: ^2.7.6


dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
